export const ENV = {
  MODE: process.env.NODE_ENV,
  IS_DEV: process.env.NODE_ENV === "development",
  IS_PROD: process.env.NODE_ENV === "production",
  API_URL: process.env.REACT_APP_FIREBASE_APP_ID,
  FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN :process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID : process.env.REACT_APP_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET : process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID:process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID:process.env.REACT_APP_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID : process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
}


/*
REACT_APP_GENERATE_SOURCEMAP=false
REACT_APP_FIREBASE_API_KEY=AIzaSyDUNce_7HDkFNhLzl8vuD9P8gT6Vq9zyj0
REACT_APP_FIREBASE_AUTH_DOMAIN= portifolio-c959d.firebaseapp.com
REACT_APP_FIREBASE_PROJECT_ID=portifolio-c959d
REACT_APP_FIREBASE_STORAGE_BUCKET=portifolio-c959d.firebasestorage.app
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=541367328221
REACT_APP_FIREBASE_APP_ID=1:541367328221:web:7253e43a859cbe15fcea34
REACT_APP_FIREBASE_MEASUREMENT_ID=G-6TW1E4WE25
REACT_APP_API_URL=http://localhost:3000
*/